Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.boot_timeout = 1200
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb2|
    vb2.memory = "1024"
    vb2.cpus = 1
  end

  config.vm.provision "shell", path: "./desplegar.sh" , privileged: false
  # Provisionamiento con Ansible
  config.vm.provision "ansible_local" do |ansiblep|
      ansiblep.playbook = "playbook.yml"
      ansiblep.verbose = "v"
  end

end