Vagrant.configure("2") do |config|
  config.vm.define "booklibrary_server" do |web| #nombre de la maquina virtual
    config.vm.box = "ubuntu/jammy64"
    config.vm.network "private_network", ip: "192.168.86.13"

    #config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 8000, host: 8080, host_ip: "127.0.0.1"

  web.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  web.vm.provision "shell", path: "./scripts/desplegar_app.sh"
end

end