Vagrant.configure("2") do |config|
    config.vm.boot_timeout = 1200
    config.vm.box_check_update = false
    config.vm.define "host1_server" do |server1|
        server1.vm.box = "ubuntu/jammy64"
        server1.vm.network "private_network", ip: "192.168.86.14"
        server1.vm.network "forwarded_port", guest: 80, host: 8080
        server1.vm.hostname = "host1"
        server1.vm.provider "virtualbox" do |vb1|
            vb1.memory = "1024"
            vb1.cpus = 1
        end
    end
    
    config.vm.define "host2_server" do |server2|
        server2.vm.box = "ubuntu/jammy64"
        server2.vm.network "private_network", ip: "192.168.86.15"
        server2.vm.network "forwarded_port", guest: 80, host: 8081
        server2.vm.hostname = "host2"
        server2.vm.provider "virtualbox" do |vb2|
            vb2.memory = "1024"
            vb2.cpus = 1
        end
    end

    config.vm.define "ansible_server" do |ansible| #nombre de la maquina virtual
        ansible.vm.box = "ubuntu/jammy64"
        ansible.vm.box_check_update = false
        ansible.vm.network "private_network", ip: "192.168.86.13"
        ansible.vm.hostname = "ansible"
        config.vm.network "forwarded_port", guest: 80, host: 8080
        #config.vm.network "forwarded_port", guest: 8000, host: 8080, host_ip: "127.0.0.1"

        ansible.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 2
        end

        # 👉 Mapea la carpeta .vagrant (donde están las claves)
        #ansible.vm.synced_folder ".", "/vagrant_data", type: "virtualbox", id: 'vagrant_data'
        #ansible.vm.synced_folder "playbooks", "/playbooks", id: "playbooks"

        ansible.vm.provision "shell", path: "./desplegar.sh" , privileged: false

        #correr ansible en la maquina guest
        ansible.vm.provision "ansible_local" do |ansiblep|
            ansiblep.playbook = "playbook.yml"
            ansiblep.verbose = "v"
        end

        # if Vagrant::Util::Platform.windows?
        #     config.vm.provision :guest_ansible do |guest_ansible|
        #     guest_ansible.playbook = "playbook.yml"
        #     end
        # else
        #     config.vm.provision :ansible do |guest_ansible|
        #     guest_ansible.playbook = "playbook.yml"
        #     end
        # end
    end

end