---
- name: Despliegue Fullstack Voting App
  hosts: all
  become: true

  vars:
    repo_url: "https://github.com/roxsross/roxs-devops-project90.git"

  tasks:

    - name: Instalar dependencias basicas
      apt:
        update_cache: yes
        name:
          - git
          - python3-venv
          - python3-dev
          - python3-pip
          - build-essential
          - curl
          - gnupg
          - python3-virtualenv
        state: present

    - name: Instalar node js
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_22.x | bash - 
        apt-get install -y nodejs
    
    - name: Instalar Redis
      apt:
        name: redis-server
        state: present

    - name: Instalar PostgreSQL
      apt:
        name: postgresql
        state: present
    
    - name: Asegurarse de que Redis y PostgreSQL estén activos
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - redis-server
        - postgresql
