
Vagrant.configure("2") do |config|
  config.vm.define "nodeapp_server" do |nodeserver| #nombre de la maquina virtual
    config.vm.box = "ubuntu/focal64"
    config.vm.box_version = "20240821.0.1"
    config.vm.boot_timeout = 900

    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.network "forwarded_port", guest: 3000, host: 8080, host_ip: "127.0.0.1"

  nodeserver.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  nodeserver.vm.provision "shell", path: "./scripts/desplegar_app.sh"

end

end
