Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.boot_timeout = 1200

  config.vm.define "node1" do |server1|
      server1.vm.network "private_network", ip: "192.168.86.14"
      server1.vm.network "forwarded_port", guest: 80, host: 8081
      server1.vm.hostname = "node1"
      server1.vm.provider "virtualbox" do |vb1|
          vb1.memory = "1024"
          vb1.cpus = 1
      end
  end

  config.vm.define "node2" do |server2|
      server2.vm.network "private_network", ip: "192.168.86.15"
      server2.vm.network "forwarded_port", guest: 80, host: 8082
      server2.vm.hostname = "node2"
      server2.vm.provider "virtualbox" do |vb2|
          vb2.memory = "1024"
          vb2.cpus = 1
      end
  end

  config.vm.define "ansible_server" do |ansible| #nombre de la maquina virtual
        ansible.vm.box_check_update = false
        ansible.vm.network "private_network", ip: "192.168.86.13"
        ansible.vm.hostname = "ansible"

        ansible.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 2
        end


        ansible.vm.provision "shell", path: "scripts/desplegar.sh" , privileged: false

        #correr ansible en la maquina guest
        ansible.vm.provision "ansible_local" do |ansiblep|
            ansiblep.playbook = "playbook.yml"
            ansiblep.galaxy_roles_path = "roles/"
            ansiblep.verbose = true
            ansiblep.limit          = "node1"
            ansiblep.inventory_path = "inventories/vagrant/host.ini"
        end

    end

end

# Para solucionar el problema en windows de los permisos de la llave, ingresar al ansible_server y ejecutar
# cp /vagrant/.vagrant/machines/node1/virtualbox/private_key ~/.ssh/vagrant_node1_key
# cp /vagrant/.vagrant/machines/node2/virtualbox/private_key ~/.ssh/vagrant_node2_key
# chmod 600 ~/.ssh/vagrant_node1_key
# chmod 600 ~/.ssh/vagrant_node2_key