Vagrant.configure("2") do |config|
  # Usa una imagen ligera de Ubuntu 22.04
  config.vm.box = "ubuntu/jammy64"
  
  # Configuración de red (accesible via IP)
  config.vm.network "private_network", ip: "192.168.86.13"
  
  # Provisionamiento con Shell
  config.vm.provision "shell", inline: <<-SHELL
    # Instalar Docker
    apt update
    apt install -y docker.io
    systemctl enable --now docker
    
    # Instalar kubectl
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    
    # Verificar
    docker --version && kubectl version --client
SHELL
end